"""init migration

Revision ID: 62289925fa14
Revises:
Create Date: 2024-06-14 17:06:52.998340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62289925fa14"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("community_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_community_id"), "community", ["id"], unique=False)
    op.create_table(
        "profile",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("check_community", sa.Boolean(), nullable=False),
        sa.Column("master_link", sa.Uuid(), nullable=False),
        sa.Column("community_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["community_id"], ["community.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_profile_community_id"), "profile", ["community_id"], unique=False
    )
    op.create_index(op.f("ix_profile_id"), "profile", ["id"], unique=False)
    op.create_table(
        "result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("image_link", sa.String(), nullable=False),
        sa.Column("profile_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_result_id"), "result", ["id"], unique=False)
    op.create_index(
        op.f("ix_result_profile_id"), "result", ["profile_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_result_profile_id"), table_name="result")
    op.drop_index(op.f("ix_result_id"), table_name="result")
    op.drop_table("result")
    op.drop_index(op.f("ix_profile_id"), table_name="profile")
    op.drop_index(op.f("ix_profile_community_id"), table_name="profile")
    op.drop_table("profile")
    op.drop_index(op.f("ix_community_id"), table_name="community")
    op.drop_table("community")
    # ### end Alembic commands ###
